version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - db
