# Generated by Django 3.2.9 on 2021-11-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0002_auto_20200211_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
