# Generated by Django 4.0 on 2021-12-29 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0009_alter_message_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 22, 27, 46, 600933, tzinfo=utc)),
        ),
    ]
