# Generated by Django 4.0 on 2021-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0005_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
